AllCops:
  RunRailsCops: true
  Excludes:
    - db/schema.rb
    - vendor/bundle/**/*
    - bin/*
Lint/AssignmentInCondition:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/MethodLength:
  Max: 44

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 10
